### ISSUE TITLE
分享title 为undefined是什么情况呢？

### ISSUE THREAD

**Issue by PccCodesix** [overtrue/share.js#116]
![_15290285683718](https://user-images.githubusercontent.com/29922883/41446800-41dea0d8-7084-11e8-8672-43233a2ecb46.png)
title 有值 为何显示undefined

**Comment by overtrue** [comment]
你尝试将你的 localhost 的地址换成其它线上服务器地址试一下

**Comment by PccCodesix** [comment]
嗯 ，换 成线上的可以了。thanks
