### ISSUE TITLE
js里面的share.js有错误

### ISSUE THREAD

**Issue by gfd6th** [overtrue/share.js#12]
更新一下，是我的错。你的npm包里面的才有问题，github上面的没有问题。
没有留意

147行
`for($key in $data){` 应该是`for(var $key in $data){`
79行
`for ($i in $data.mode == 'prepend' ? $sites.reverse() : $sites) {`
应该是
`for (var $i in $data.mode == 'prepend' ? $sites.reverse() : $sites) {`

都少了var，有时候会报错

**Comment by overtrue** [comment]
@gfd6th 升级了一下版本，请更新再试
