### ISSUE TITLE
分享次数

### ISSUE THREAD

**Issue by wordStart** [overtrue/share.js#132]
同一页面，分享多次，只显示最一开始分享的那一条，接着分享多次，之后的不会显示出来，请问一下这个是插件的问题，还是qq空间那边做了什么限制？

**Comment by overtrue** [comment]
这个插件只是生成一个分享链接哈，没有任何逻辑哈

wordStart <notifications@github.com>于2019年2月12日 周二下午2:00写道：

**Comment by wordStart** [comment]
感谢，那么这个是空间那边做了限制么？

**Comment by wordStart** [comment]
Thanks
