### ISSUE TITLE
Safari下options失效

### ISSUE THREAD

**Issue by sxcooler** [overtrue/share.js#24]
您好，再打扰一下：
Chrome和Safari下Object$assign.apply()的实现似乎不太一致：
我的代码：
\<div className="social-share" data-sites="weibo,wechat"/\>
在Chrome下能正确只显示微博微信，Safari下则全部显示。

调试过程如下：
![2016-03-16 11 36 04](https://cloud.githubusercontent.com/assets/3192045/13801345/f0627da0-eb6b-11e5-9c9d-61621a7359ca.png)
这是断点位置，

![2016-03-16 11 36 20](https://cloud.githubusercontent.com/assets/3192045/13801352/023b9340-eb6c-11e5-92c1-b1bbee275fe4.png)
这是Chrome下的test对象，

<img width="306" alt="2016-03-16 11 37 16" src="https://cloud.githubusercontent.com/assets/3192045/13801378/1ad9987a-eb6c-11e5-9d2a-76754c88baa3.png">
这是Safari下。

操作系统：OS X 10.11.3

我暂时是把Object$assign这段注掉解决的，不知道有没有更好的办法，所以就不提pull request了。

再次感谢您做了这些方便大家的工作。

**Comment by overtrue** [comment]
@sxcooler 那先将就用着吧，我打算找个时间重构一下，现在的代码不满意。有使用上的建议或者想要增加的 feature 欢迎 issue. :smile:
