### ISSUE TITLE
master分支的字体库不起作用

### ISSUE THREAD

**Issue by longmen21** [overtrue/share.js#3]
### master分支的字体库不起作用，您能check一下吗？

**Comment by overtrue** [comment]
不起作用？？？？

**Comment by longmen21** [comment]
恩 我去您的博客重新down的字体

**Comment by overtrue** [comment]
https://github.com/overtrue/share.js/commit/bc2b74f6d773032af1b7df730dc5025c2d310f0e

我写了 [example.html](https://github.com/overtrue/share.js/blob/master/example.html) 你可以试试。
