### ISSUE TITLE
字体冲突

### ISSUE THREAD

**Issue by JayzeeHuang** [overtrue/share.js#33]
css自定义字体后就不显示图标
  `font-family: Tahoma, Helvetica, Arial, "Microsoft Yahei","微软雅黑", STXihei, "华文细黑", sans-serif;`

**Comment by overtrue** [comment]
你当然不能对icon再定义字体啊

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.11.38&pv=10.11.5&source=email_footer_2]
On 周一, 5月 16, 2016 at 4:37 下午, JayzeeHuang <notifications@github.com> wrote:
css自定义字体后就不显示图标
font-family: Tahoma, Helvetica, Arial, "Microsoft Yahei","微软雅黑", STXihei, "华文细黑", sans-serif;

**Comment by JayzeeHuang** [comment]
我是定义下面几个元素的字体
```
a, body, button, div, h1, h2, h3, h4, h5, h6, input, label, li, p, textarea, td, th, select {
    font-family: Tahoma, Helvetica, Arial, "Microsoft Yahei","微软雅黑", STXihei, "华文细黑", sans-serif;
}
```
没有对图标定义字体  
只要CSS有那句话就不显示图标了

**Comment by overtrue** [comment]
试一下加一句：

.social-share * { font-family:"socialshare" !important; }
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.11.38&pv=10.11.5&source=email_footer_2]
On 周一, 5月 16, 2016 at 4:55 下午, JayzeeHuang <notifications@github.com> wrote:
我是定义下面几个元素的字体

a, body, button, div, h1, h2, h3, h4, h5, h6, input, label, li, p, textarea, td, th, select {
    font-family: Tahoma, Helvetica, Arial, "Microsoft Yahei","微软雅黑", STXihei, "华文细黑", sans-serif;
}


没有对图标定义字体

只要CSS有那句话就不显示图标了

**Comment by JayzeeHuang** [comment]
@overtrue solved! thanks.

**Comment by overtrue** [comment]
@JayzeeHuang 如果你用的npm安装的，可以升级到1.0.14了
