### ISSUE TITLE
如何改变分享按钮的顺序

### ISSUE THREAD

**Issue by freedomlang** [overtrue/share.js#34]
翻看了一下文档，不知如何改变分享按钮的顺序，不知道是不是我没看到！

**Comment by overtrue** [comment]
@freedomlang 你可以用 `data-sites` 属性指定：
```html
data-sites="weibo,qq,facebook,google ... " 
```

**Comment by freedomlang** [comment]
@overtrue 可以了

**Comment by freedomlang** [comment]
@overtrue data-sites和data-disable一起使用会冲突，导致没有没有图标显示！这两者单独使用就没问题！

**Comment by overtrue** [comment]
@freedomlang 贴代码或者给链接

**Comment by freedomlang** [comment]
抱歉，项目还没上线，连接暂时没有！代码如下
```
<div class="social-share" data-sites="wechat,qq,weibo" data-mobile-sites="weibo,qq,qzone,tencent" data-disabled="douban,qzone,diandian,google,twitter,facebook,linkedin,tencent" data-wechat-qrcode-title="请打开微信扫一扫" data-wechat-qrcode-helper=""> </div>
```

**Comment by freedomlang** [comment]
@overtrue 补充截图
![Screenshot from 2016-06-06 09:50:54.png][1]
[1]: http://blog.freedomlang.com/usr/uploads/2016/06/2135392775.png

**Comment by overtrue** [comment]
@freedomlang 其实你不需要 `disabled` 吧，试一下删除它。

**Comment by freedomlang** [comment]
@overtrue 这两个单独使用都是没有问题的，建议取消data-disable？因为data-sites已经有data-disable的功能了

**Comment by overtrue** [comment]
@freedomlang NO，`sites` 如果后期我加入其它的，一共20来个的时候，你只想禁用一个，你用sites把我的20多个写一遍？这其实是一个白名单与黑名单的设计了。肯定都有它的好处。

**Comment by freedomlang** [comment]
@overtrue 也是^_^

**Comment by overtrue** [comment]
@freedomlang 😄
