### ISSUE TITLE
分享到QQ  QQ没有反应 是什么问题 

### ISSUE THREAD

**Issue by ljkfgh2008** [overtrue/share.js#36]
用您的组件分享到QQ QQ没有提示 是否是QQ的问题

**Comment by freedomlang** [comment]
没有提示具体指什么？

**Comment by zhyocean** [comment]
为什么我跳到分享QQ好友那后点击分享就分享失败了呀

**Comment by overtrue** [comment]
@zhyocean 这个组件只是生成一个链接到分享页面而已，至于跳过去以后的东西管不了。

**Comment by zhyocean** [comment]
@overtrue 确实跳到分享页面了,但是我选择要发送的好友后点击发送弹出个验证码，我输入了后就直接跳到发送失败了，而且我看了你的那个demo好像也是发送给QQ好友会发送失败

**Comment by overtrue** [comment]
我上面已经说了，跳过去以后的逻辑我管不着，那是腾讯的代码

zhy_ocean <notifications@github.com>于2018年9月17日 周一下午3:19写道：
