### ISSUE TITLE
js获取页面Url的问题

### ISSUE THREAD

**Issue by longmen21** [overtrue/share.js#4]
### js获取页面URL，最好之后再urlencode一下，可能url里面有符号

**Comment by overtrue** [comment]
https://github.com/overtrue/share.js/commit/bc2b74f6d773032af1b7df730dc5025c2d310f0e

**Comment by overtrue** [comment]
https://github.com/overtrue/share.js/commit/bc2b74f6d773032af1b7df730dc5025c2d310f0e
