### ISSUE TITLE
<meta name="site" content="{{$title or ''}}" />无效，data-source='test'也无效

### ISSUE THREAD

**Issue by gewuxy** [overtrue/share.js#42]
如下图：
![qq20160816-0 2x](https://cloud.githubusercontent.com/assets/8190691/17694028/6ccc50c4-63d4-11e6-8be3-d7129dbdd1c8.png)
我按照引导设置了<meta name="site" content="{{$title or ''}}" />无效，
设置data-source='test'也无效。

**Comment by gewuxy** [comment]
很奇怪为什么会出现：忘记密码这样的文案

**Comment by gewuxy** [comment]
我测试了下，在网址中把source="xxxx"换成summary="xxxx"就可以正常显示，但是我看http://overtrue.me/share.js/上QQ分享网址并没有summary字段，不知share.js是怎么处理的

**Comment by gewuxy** [comment]
看了social-share.js的源码，是bug，template中
qq: 'http://connect.qq.com/widget/shareqq/index.html?url={{URL}}&title={{TITLE}}&source={{SOURCE}}&desc={{DESCRIPTION}}&pics={{IMAGE}}',
少了summary字段，我修改后直接用这个文件，可是还是有其他问题，图标被重复渲染三次，导致出现一堆重复的图标等，可以修复下重发一个吗，麻烦了哈

**Comment by gewuxy** [comment]
问题我自己暂时修复了

**Comment by yuweilan** [comment]
我遇到跟楼主一样的问题，
找到qq: 'http://connect.qq.com/widget/shareqq/index.html?url={{URL}}&title={{TITLE}}&source={{SOURCE}}&desc={{DESCRIPTION}}&pics={{IMAGE}}',
改为qq: 'http://connect.qq.com/widget/shareqq/index.html?url={{URL}}&title={{TITLE}}&summary={{SOURCE}}&desc={{DESCRIPTION}}&pics={{IMAGE}}',字段仍使用source暂时解决了
