### ISSUE TITLE
在手机端分享时不能直接调起QQ和微信app分享吗？

### ISSUE THREAD

**Issue by gewuxy** [overtrue/share.js#43]
弱弱的问下，在手机端分享时不能直接调起QQ和微信app分享吗？感觉很不人性化

**Comment by overtrue** [comment]
overtrue.me. 我的在手机分享就可以，为啥呢？

On 周三, 8月 17, 2016 at 9:46 上午, gewuxy <notifications@github.com> wrote:
弱弱的问下，在手机端分享时不能直接调起QQ和微信app分享吗？感觉很不人性化

**Comment by gewuxy** [comment]
是吗，我试了下你的网站，微信分享是直接出现二维码框，QQ分享是跳到登录界面，都没有把app调起来，我的是android一加手机，你的呢

**Comment by gewuxy** [comment]
微博可以调起app

**Comment by overtrue** [comment]
@gewuxy 本来就调不起 QQ 啊。。。

**Comment by overtrue** [comment]
@gewuxy 那是 QQ 自己做的啊，微博与 QQ 都是一样，跳到一个 URL, 不过微博加了一个判断 app 的逻辑 。。。

**Comment by gewuxy** [comment]
@overtrue 那为什么今日头条可以调起app呢？

**Comment by overtrue** [comment]
@gewuxy 来个网页

**Comment by gewuxy** [comment]
http://sc.qq.com/fx/u?r=ZEJCqeA

**Comment by overtrue** [comment]
这个页面没发现分享按钮。。。

On 周三, 8月 17, 2016 at 10:15 上午, gewuxy <notifications@github.com> wrote:
http://sc.qq.com/fx/u?r=ZEJCqeA [http://sc.qq.com/fx/u?r=ZEJCqeA]

**Comment by gewuxy** [comment]
在手机浏览器中打开，不要用微信

**Comment by overtrue** [comment]
抱歉，用任何浏览器都没发现分享按钮。

On 周三, 8月 17, 2016 at 11:18 上午, gewuxy <notifications@github.com> wrote:
在手机浏览器中打开，不要用微信

**Comment by gewuxy** [comment]
先不管这个问题了，我想问下src目录下的social-share.js和那些压缩过的min.js是不是有差别，我为了修复QQ分享缺少summary字段的问题用了这个文件，
但是发现有不少兼容性问题，如data-disabled在Safari无效，另外在Safari中QQ分享summary和description字段也是空的，chrome正常

注：
昨天一开始遇到的QQ分享卡片文案错误的问题估计就是summary字段为空的问题（chrome是读到了，但是其他浏览器是空的），所以QQ才自己去首页抓取的文案。

测试例子：
http://www.gewuxy.com/course/1/grade/1/chapter/1/tutorial/1

**Comment by overtrue** [comment]
其中有一个不依赖 jQ 的版本是别人写的。兼容性问题也许存在，建议使用 jQ 版本。

On 周三, 8月 17, 2016 at 5:09 下午, gewuxy <notifications@github.com> wrote:
先不管这个问题了，我想问下src目录下的social-share.js和那些压缩过的min.js是不是有差别，我为了修复QQ分享缺少summary字段的问题用了这个文件，
但是发现有不少兼容性问题，如data-disabled在Safari无效，另外在Safari中QQ分享summary和description字段也是空的，chrome正常

注：
昨天一开始遇到的QQ分享卡片文案错误的问题估计就是summary字段为空的问题（chrome是读到了，但是其他浏览器是空的），所以QQ才自己去首页抓取的文案。

测试例子：
http://www.gewuxy.com/course/1/grade/1/chapter/1/tutorial/1 [http://www.gewuxy.com/course/1/grade/1/chapter/1/tutorial/1]

**Comment by gewuxy** [comment]
jquery.share.js:134 Uncaught TypeError: $wechat.find(...).qrcode is not a function,报qrcode方法找不到

**Comment by overtrue** [comment]
@gewuxy 请使用 dist 下的文件。

**Comment by gewuxy** [comment]
dist下的是jquery.share.min.js，正如我一开始说的，QQ分享少了summary字段，用min版本没办法修改啊

**Comment by overtrue** [comment]
先将就用吧，过几天我重构一下。

On 周三, 8月 17, 2016 at 8:37 下午, gewuxy <notifications@github.com> wrote:
dist下的是jquery.share.min.js，正如我一开始说的，QQ分享少了summary字段，用min版本没办法修改啊

**Comment by gewuxy** [comment]
哎，我也不是很懂javascript，怎么才能学到那么高深的层次

**Comment by overtrue** [comment]
各种折腾就好了，逼自己完成。哈哈

On 周三, 8月 17, 2016 at 8:40 下午, gewuxy <notifications@github.com> wrote:
哎，我也不是很懂javascript，怎么才能学到那么高深的层次

**Comment by gewuxy** [comment]
折腾了两天，还是得等你更新代码了。。。

**Comment by gewuxy** [comment]
或者你跟我说说该怎么修复这个错误，我也学习一下

**Comment by overtrue** [comment]
@gewuxy 去 safari 里调试，看看为啥没去到，然后改掉。我也没有具体的解决方法，只有去具体看才知道，手里在忙其它项目，所以还得等一段时间了。

**Comment by gewuxy** [comment]
@overtrue 不是，我现在是想解决qrcode方法找不到的问题，导入qrcode.js没用

**Comment by overtrue** [comment]
在引入我的文件之前先引入那个 qrcode js 就好了。

**Comment by gewuxy** [comment]
<script src="/shareJS/js/qrcode.js"></script>
    <script src="/shareJS/js/jquery.share.js"></script>，
不行哦

**Comment by gewuxy** [comment]
其实我觉得qrcode.js应该是javascript版本，缺少一个jquery版本
