### ISSUE TITLE
希望在移动端分享时能够调用APP分享

### ISSUE THREAD

**Issue by waleswood** [overtrue/share.js#45]
统一分享风格，图片缩略图等。

**Comment by overtrue** [comment]
@waleswood 调用 APP 分享是需要 原生应用的 SDK 才行的，不是网页能搞定的。。。

**Comment by waleswood** [comment]
可以借用借用UC浏览器或者QQ浏览器或者URL scheme进行，这有个实现的例子https://github.com/calledT/sosh
https://github.com/ninetylai/SocialShare
