### ISSUE TITLE
QQ分享出现很神奇的问题

### ISSUE THREAD

**Issue by CeBkCn** [overtrue/share.js#48]
最开始使用一切正常，http://overtrue.me/share.js/和自己自定义的页面在PC和手机上都没有问题，正常使用的情况大概有5天左右，期间分享给QQ好友2次，点开分享后取消若干次，在分享页登录过QQ，这期间电脑未重启过，关机使用休眠。
大概5天过后问题来了，无论是http://overtrue.me/share.js/还是自定义页面的QQ分享出现ERR_CONNECTION_TIMED_OUT，手机和PC都是这样。
使用goagent挂代理后，http://overtrue.me/share.js/和自定义页面都可以正常分享。
重启路由器，重启PC，http://overtrue.me/share.js/页面正常，自定义页面问题依旧。
重启手机，http://overtrue.me/share.js/和自定义页面问题依旧，断开wifi**使用流量**，http://overtrue.me/share.js/和自定义页面均可以正常使用。
一脸懵逼，是我自身的网络问题吗？然而一开始使用却没有任何问题啊。。。

**Comment by overtrue** [comment]
@CeBkCn 本组件只是生成 a 标签的 dom 而已，与网络无关。
