### ISSUE TITLE
获取网页的Logo

### ISSUE THREAD

**Issue by longmen21** [overtrue/share.js#6]
有的logo可能是以相对路径的方式引入的
建议这样写： 
var $image = window.location.host + $(document).find('img:first').attr('src');

**Comment by overtrue** [comment]
```js
$(document).find('img:first').prop('src');
```
才是科学的 :smile:

**Comment by overtrue** [comment]
https://github.com/overtrue/share.js/commit/2a7ecfd447ceead48fcccf7c82185a86eeece3db

**Comment by longmen21** [comment]
![image](https://cloud.githubusercontent.com/assets/10226813/10685586/35a04938-798e-11e5-9dc1-660157b48cc8.png)
