### ISSUE TITLE
生成的分享链接无法使用屏幕阅读器朗读

### ISSUE THREAD

**Issue by vgjh2005** [overtrue/share.js#60]
你好：
我是译名盲人朋友，正在搭建自己的博客。偶然间发现了你创建的项目share.js,感觉很方便。不过，生成出来的链接都读不了呢，因为链接都是以图片形式展示的。为了不影响美观还能让盲人朋友用户用上这个脚本，希望可以给链接加入aria-label属性哦。这个属性的好处是，不影响外观，而能给视障用户使用的屏幕阅读器设置好相应的读取信息。
非常感谢！

**Comment by overtrue** [comment]
@vgjh2005 好的，感谢反馈

**Comment by vgjh2005** [comment]
谢谢！

**Comment by overtrue** [comment]
@vgjh2005 jQuery 版本已经支持了。
