### ISSUE TITLE
微博分享自动抓图失败

### ISSUE THREAD

**Issue by hitrust** [overtrue/share.js#62]
首先感谢作者分享和奉献。
在全站启用https站点，微博分享自动抓图功能，只能抓取到网站logo图片，并且logo图片不显示；
在非全站启用https站点，则没有这个问题。
那么，请问问题是不是出在微博分享这边呀?
![2017-01-22_103647](https://cloud.githubusercontent.com/assets/3360631/22179443/d49fa98a-e08e-11e6-8799-28591cb3a216.png)
![2017-01-22_103625](https://cloud.githubusercontent.com/assets/3360631/22179444/d679f8aa-e08e-11e6-9453-e2875984df61.png)

**Comment by overtrue** [comment]
那肯定了
