### ISSUE TITLE
分享QQ和QQ空间都没反应

### ISSUE THREAD

**Issue by javayangzhen** [overtrue/share.js#63]
![cb3983ilyerm9b shf77183](https://cloud.githubusercontent.com/assets/22785456/22625162/7220b3a8-ebc9-11e6-97b1-3ce388187e8b.png)
![l 9dd hrdci p3b noh _3](https://cloud.githubusercontent.com/assets/22785456/22625165/8db99c2e-ebc9-11e6-96f5-8a6651a47071.png)

**Comment by overtrue** [comment]
已经跳到该页面证明我的 lib 没有问题，谢谢！
