### ISSUE TITLE
在Firefox下点击微信二维码会弹出空的新标签页，并且页面上会留下虚线边框。

### ISSUE THREAD

**Issue by ScienJus** [overtrue/share.js#7]
如图所示：

![虚线][1]

[1]: http://www.scienjus.com/wp-content/uploads/2015/12/1.png

简单看了下，如果在

```
<a href="javascript:;" class="iconfont icon-wechat" target="_blank">
```

这个`a`标签添加一个`onclick`属性，就不会弹出新的标签页了。

```
<a href="javascript:;" class="iconfont icon-wechat" target="_blank" onclick="return false;">
```

但是点击后还是会出现虚线，麻烦作者有时间修复一下这个不太起眼的问题，多加感谢。

**Comment by overtrue** [comment]
收到 http://blog.codemonkey.cn/archives/269
