### ISSUE TITLE
IE11 会有报错，是不是不支持IE的？

### ISSUE THREAD

**Issue by Fred0715** [overtrue/share.js#71]
无法获取未定义或 null 引用的属性“appendChild

**Comment by qiqihaobenben** [comment]
就调整一行代码就行了，ie下appendChild后，把之前获取的DOM清空了。本来想给你截个图，上传不了，这个我已经提了pr了。有类似问题可以在下面留言。

**Comment by overtrue** [comment]
@no-simple 抱歉没考虑 IE 😆

**Comment by no-simple** [comment]
@overtrue 只有微信分享 在IE报错了   可以更完美的

**Comment by qiqihaobenben** [comment]
项目地址：https://github.com/qiqihaobenben/xgx-share
npm地址： https://www.npmjs.com/package/vue-xueguoxue-share
