### ISSUE TITLE
是bug还是我的使用姿势不对?

### ISSUE THREAD

**Issue by wewea** [overtrue/share.js#8]
我要这样用才能有效果
```javascript
// 配置要放第二个参数
$('share-bar').share({}, $options);

```
我看了一下源码, 发现没有用到第一个参数啊. 是我使用姿势有问题还是bug啊?

**Comment by overtrue** [comment]
@wewea sorry是Bug,更新时忘记参数问题了，谢谢提醒，已经fix.

**Comment by overtrue** [comment]
@wewea https://github.com/overtrue/share.js/commit/2ee32593621941b61e930b0498fe9ef6138fb1f4
