### ISSUE TITLE
a 标签必须带 icon-NAME 属性加在哪里,有详细demo吗

### ISSUE THREAD

**Issue by shmilyxwx** [overtrue/share.js#84]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="../dist/css/share.min.css"/>
		<title></title>
	</head>
	<body>
		<div class="social-share" data-initialized="true">
			<a icon-NAME href="#" class="social-share-icon icon-weibo"></a>
			<a icon-NAME href="#" class="social-share-icon icon-qq"></a>
			<a icon-NAME href="#" class="social-share-icon icon-qzone"></a>
		</div>
		<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
		<script src="../dist/js/jquery.share.min.js" type="text/javascript" charset="utf-8"></script>
		<script type="text/javascript">
			var $config = { 
				url:"http://www.baidu.com"
				};
			$('.social-share').share($config);
		</script>
	</body>
</html>
怎么没有跳转功能
这个 icon-NAME到底家在哪里

**Comment by overtrue** [comment]
'weibo', 'qq', 'wechat', 'tencent', 'douban', 'qzone', 'linkedin', 'diandian', 'facebook', 'twitter', 'google'
