### ISSUE TITLE
通过Ajax载入的文章不能加载分享数据

### ISSUE THREAD

**Issue by hitrust** [overtrue/share.js#88]
如题，上面的图片是正常能加载，下面的图是通过Ajax加载的，不能加载分享数据
![2017-09-04_113636](https://user-images.githubusercontent.com/3360631/30010849-81722c14-9165-11e7-9bce-e271682e42fb.png)
![2017-09-04_113723](https://user-images.githubusercontent.com/3360631/30010852-81a5c6be-9165-11e7-858b-2668a8871fad.png)

调用(".share-component,.social-share").share()，好像也不行。

**Comment by overtrue** [comment]
配置参数里有传图片路径，至于你是怎么加载图片与这个无关吧，你只要把图片路径正确的传到 配置参数就好

如果你的 data-image 要 ajax 异步，那就应该是 图片加载完才去初始化  share 控件才对。

**Comment by hitrust** [comment]
感谢提示，问题已解决。
